version: '3.8'

services:
  postgres_db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=crypto_user
      - POSTGRES_DB=crypto_order
    ports: 
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgres

volumes:
  postgres_volume: