version: '3.8'

services:
  postgres_db:
    image: postgres:16.2
    env_file:
      - .env
    ports: 
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgres

volumes:
  postgres_volume: